title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://media.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com
image: "https://crds-cms-uploads.imgix.net/content/images/cr-social-sharing-still-bg.jpg"

# disable_hubspot: true
permalink: /:title/

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-contentful

# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - package.json
  - README.md
  - spec
  - tmp
  - vendor

include:
  - _redirects

collections_dir: collections

collections:
  articles:
    output: true
    permalink: /:collection/:title
  topics:
    output: true
    permalink: /:collection/:title
  authors:
    output: true
    permalink: /:collection/:title
  podcasts:
    output: true
    permalink: /:collection/:title
  episodes:
    output: true
    permalink: /podcasts/:podcast_slug/:title
  albums:
    output: true
    permalink: /:collection/:title
  songs:
    output: true
    permalink: /:collection/:title
  videos:
    output: true
    permalink: /:collection/:title
  series:
    output: true
    permalink: /:collection/:title
  tags:
    output: false
  features:
    output: false
  messages:
    output: true
    permalink: /series/:series_slug/:title

contentful:
  content_types:
    articles:
      id: article
      body: body
      filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
      frontmatter:
        entry_mappings:
          title: title
          image: image/url
          author: author/full_name
          lead: lead_text
          topic: category/title
          date: published_at
          slug: slug
          tags: tags/title
        other:
          layout: article
          draft: false
    authors:
      id: author
      body: summary
      frontmatter:
        entry_mappings:
          name: full_name
          image: image/url
        other:
          layout: author
          draft: false
    topics:
      id: category
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
          image: image/url
        other:
          layout: topic
          draft: false
    podcasts:
      id: podcast
      body: description
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          image: image/url
          background: bg_image/url
          authors: author/full_name
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          stitcher_url: stitcher_url
          slug: slug
        other:
          layout: podcast
          draft: false
    episodes:
      id: episode
      body: description
      filename: "{{ episode_number }}-{{ slug }}"
      frontmatter:
        entry_mappings:
          title: title
          episode_number: episode_number
          season_number: season_number
          date: published_at
          podcast: podcast/title
          podcast_slug: podcast/slug
          image: podcast/image/url
          slug: slug
          topic: category/title
          tags: tags/title
          description: description
          show_notes: show_notes
          transcription: transcription
          audio_duration: audio_duration
          audio_embed_code: audio_embed_code
        other:
          layout: episode
          draft: false
    albums:
      id: album
      body: description
      frontmatter:
        entry_mappings:
          title: title
          date: published_at
          image: image/url
          bg_image: bg_image/url
          authors: author/full_name
          spotify_url: spotify_url
          apple_music_url: apple_music_url
          google_play_url: google_play_url
          slug: slug
        other:
          layout: album
          draft: false
    songs:
      id: song
      body: description
      frontmatter:
        entry_mappings:
          title: title
          details: details
          lyrics: lyrics
          chords: chords
          stems: stems
          topic: category/title
          topic_slug: category/slug
          tags: tags/title
          author: author/full_name
          duration: audio_duration
          album_title: album/title
          album_image: album/image/url
          album_slug: album/slug
          date: published_at
          image: image/url
          bg_image: bg_image/url
          spotify_url: spotify_url
          apple_music_url: apple_music_url
          google_play_url: google_play_url
          youtube_url: youtube_url
          related_videos: related_videos
          call_to_action: call_to_action
          featured_label: featured_label
          featured_subtitle: featured_subtitle
          slug: slug
        other:
          layout: song
          draft: false
    videos:
      id: video
      body: description
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          authors: author/full_name
          duration: video_duration
          date: published_at
          image: image/url
          source_url: source_url
          topic: category/title
          topic_slug: category/slug
          tags: tags/title
          description: description
          transcription: transcription
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          slug: slug
          view_count: view_count
        other:
          layout: video
          draft: false
    series:
      id: series
      body: description
      associations:
        videos:
          - videos
          - messages
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
          image: image/url
          bg_image: background_image/url
          date: starts_at
          start_date: starts_at
          end_date: ends_at
          youtube_url: youtube_url
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          year: "{{ starts_at | date: '%Y' }}"
          videos: videos/id
        other:
          layout: series
          draft: false
    tags:
      id: tag
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
          video_collection: video_collection
    features:
      id: featured_media
      frontmatter:
        entry_mappings:
          title: title
          page_path: path
          doc_ids: entries/id
    messages:
      id: message
      body: description
      links:
        series_slug:
          content_type: series
          field: videos
          value: slug
      frontmatter:
        entry_mappings:
          title: title
          authors: author/full_name
          image: image/url
          source_url: source_url
          audio_source_url: audio_source_url
          program_url: program/url
          video_duration: video_duration
          topic: category/title
          topic_slug: category/slug
          tags: tags/title
          description: description
          transcription: transcription
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          date: published_at
          slug: slug
        other:
          layout: video
          draft: false

defaults:
  - scope:
      path: ""
    values:
      js_manifest: application_deferred
  - scope:
      path: "/articles"
      type: articles
    values:
      layout: article
  - scope:
      path: "/topics"
      type: topics
    values:
      layout: topic
  - scope:
      path: "/authors"
      type: authors
    values:
      layout: author
  - scope:
      path: "/podcasts"
      type: podcasts
    values:
      layout: podcast
  - scope:
      path: "/episodes"
      type: episodes
    values:
      layout: episode
  - scope:
      path: "/videos"
      type: videos
    values:
      layout: video
  - scope:
      path: "/series"
      type: series
    values:
      layout: series
  - scope:
      path: "/messages"
      type: messages
    values:
      layout: video

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  js_compressor: uglifier
  sources:
  - _assets/stylesheets
  - _assets/javascripts

imgix_params:
  placeholder: "auto=format,compress&w=10"
  placeholder_card: "auto=format,compress&w=12&h=9&fit=crop"
  placeholder_square: "auto=format,compress&w=10&h=10&fit=crop"
  placeholder_sixteen_nine: "auto=format,compress&w=16&h=9&fit=crop"

image_sizes:
  media_object: "(min-width: 768px) 140px, (min-width: 0px) 100px"
  cards_6x: "(min-width: 992px) 165px, (min-width: 0px) 50vw"
  cards_4x: "(min-width: 992px) 212.5px, (min-width: 768px) 345px, (min-width: 0px) 100vw"
  cards_3x: "(min-width: 992px) 390px, (min-width: 0px) 100vw"
  cards_3x_centered_carousel: "(min-width: 1200px) 232.5px, (min-width: 992px) 191px, (min-width: 768px) 146px, (min-width: 0px) 270px"
  cards_2x: "(min-width: 768px) 345px, (min-width: 0px) 100vw"
  music_thumb: "(min-width: 768px) 360px, (min-width: 0px) 323px"
  podcast_thumb: "(min-width: 768px) 330px, (min-width: 480px) 200px, (min-width: 0px) 100vw"
  episode_thumb: "(min-width: 768px) 120px, (min-width: 0px) 80px"
  album_thumb: "96px"
  song_artwork: "(min-width: 992px) 360px, (min-width: 0px) 100vw"
  avatar: "80px"
  full_width: "100vw"
  half_width: "50vw"
  one_hundred: "100%"
  topic_feature_sub: "(min-width: 992px) 370px, (min-width: 0px) 100px"

typekit_url: https://use.typekit.net/ccb3vpa.css
