title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://media.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com

# disable_hubspot: true
permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-contentful
  - jekyll-paginate-v2

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 16
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

# livereload: true
# reload_port: 4300

# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - _migrations

include:
  - _redirects

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /articles/:slug
  topics:
    output: true
    permalink: /topics/:path
  authors:
    output: true
    permalink: /:collection/:path
  podcasts:
    output: true
    permalink: /:collection/:slug
  episodes:
    output: true
    permalink: /:collection/:slug
 albums:
    output: true
    permalink: /:collection/:slug
  songs:
    output: true
    permalink: /:collection/:slug

contentful:
  content_types:
    posts:
      id: article
      body: body
      filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
      frontmatter:
        entry_mappings:
          title: title
          image: image/url
          author: author/full_name
          topic: category/title
          date: published_at
          slug: slug
          tags: tags
        other:
          layout: post
          draft: false
    authors:
      id: author
      body: summary
      frontmatter:
        entry_mappings:
          name: full_name
          image: image/url
        other:
          layout: author
          draft: false
    topics:
      id: category
      frontmatter:
        entry_mappings:
          title: title
        other:
          layout: topic
          draft: false
    podcasts:
      id: podcast
      body: description
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          image: image/url
          background: bg_image/url
          authors: [author, full_name]
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          stitcher_url: stitcher_url
          slug: slug
        other:
          layout: podcast
          draft: false
    episodes:
      id: episode
      body: description
      filename: "{{ episode_number }}-{{ slug }}"
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          audio_file: audio_file/url
          episode_number: episode_number
          season_number: season_number
          date: published_at
          podcast: podcast/title
          image: podcast/image/url
          slug: slug
        other:
          layout: episode
          draft: false
    albums:
      id: album
      body: description
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          date: published_at
          image: image/url
          bg_image: bg_image/url
          spotify_url: spotify
          apple_music_url: apple_music
          google_play_url: google_play
          slug: slug
        other:
          layout: album
          draft: false
    songs:
      id: song
      body: description
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          date: published_at
          album: album/title
          image: image/url
          bg_image: bg_image/url
          spotify_url: spotify
          apple_music_url: apple_music
          google_play_url: google_play
          youtube_url: youtube
          slug: slug
        other:
          layout: song
          draft: false   
            
defaults:
  - scope:
      path: "/articles"
      type: posts
    values:
      layout: post
  - scope:
      path: "/topics"
      type: topics
    values:
      layout: topic
  - scope:
      path: "/authors"
      type: authors
    values:
      layout: author
  - scope:
      path: "/podcasts"
      type: podcasts
    values:
      layout: podcast
  - scope:
      path: "/episodes"
      type: episodes
    values:
      layout: episode

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - _assets/stylesheets
  - _assets/javascripts


imgix_placeholder_args: "?w=10&auto=format,compress"

typekit_url: https://use.typekit.net/ccb3vpa.css

