title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com

# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

# disable_hubspot: true
permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-hubspot
  - jekyll-paginate-v2

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 8
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

sass:
  sass_dir: _scss

include:
  - _redirects

collections_dir: collections

collections:
  blogs:
    output: true
    permalink: /topics/:path
  authors:
    output: true
    permalink: /:collection/:path

hubspot:
  blogs:
    layout: topic
    properties:
      id: id
      title: name
      content: description
  posts:
    layout: post
    properties:
      title: title
      content: post_body
      featured_image: featured_image
      featured_image_alt: featured_image_alt_text
      author: blog_post_author/display_name
      date: publish_date
      topic: topics
  authors:
    layout: author
    properties:
      content: bio
      title: displayName
      name: displayName
      image: avatar

defaults:
  - scope:
      path: "/topics"
      type: blogs
    values:
      layout: topic
  - scope:
      path: "/authors/"
      type: authors
    values:
      layout: author

