title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://media.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com
image: "https://crds-cms-uploads.imgix.net/content/images/cr-social-sharing-still-bg.jpg"

# disable_hubspot: true
permalink: /:title/

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-contentful

# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - package.json
  - README.md
  - spec
  - tmp
  - vendor

include:
  - _redirects

collections_dir: collections

collections:
  articles:
    output: true
    permalink: /:collection/:title
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
  categories:
    output: false
    permalink: /:collection/:title
  authors:
    output: false
    permalink: /:collection/:title
  podcasts:
    output: false
    permalink: /:collection/:title
  episodes:
    output: false
    permalink: /podcasts/:podcast_slug/:title
  albums:
    output: false
    permalink: /:collection/:title
  songs:
    output: false
    permalink: /:collection/:title
  videos:
    output: false
    permalink: /:collection/:title
  series:
    output: false
    permalink: /:collection/:title
  tags:
    output: false
  features:
    output: false
  discussions:
    output: false
  messages:
    output: false
    permalink: /series/:series_slug/:title

contentful:
  exclude:
    - migrations
    - location
    - page
    - promo

defaults:
  - scope:
      path: ""
    values:
      js_manifest: application_deferred
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
      type: categories
    values:
      layout: topic
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: podcasts
    values:
      layout: podcast
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
  - scope:
      path: ""
      type: videos
    values:
      layout: video
  - scope:
      path: ""
      type: series
    values:
      layout: series
  - scope:
      path: ""
      type: messages
    values:
      layout: video

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  js_compressor: uglifier
  sources:
  - _assets/stylesheets
  - _assets/javascripts

imgix_params:
  placeholder: "auto=format,compress&w=10"
  placeholder_card: "auto=format,compress&w=12&h=9&fit=crop"
  placeholder_square: "auto=format,compress&w=10&h=10&fit=crop"
  placeholder_sixteen_nine: "auto=format,compress&w=16&h=9&fit=crop"

image_sizes:
  media_object: "(min-width: 768px) 140px, (min-width: 0px) 100px"
  cards_6x: "(min-width: 992px) 165px, (min-width: 0px) 50vw"
  cards_4x: "(min-width: 992px) 212.5px, (min-width: 768px) 345px, (min-width: 0px) 100vw"
  cards_3x: "(min-width: 992px) 390px, (min-width: 0px) 100vw"
  cards_3x_centered_carousel: "(min-width: 1200px) 232.5px, (min-width: 992px) 191px, (min-width: 768px) 146px, (min-width: 0px) 270px"
  cards_2x: "(min-width: 768px) 345px, (min-width: 0px) 100vw"
  music_thumb: "(min-width: 768px) 360px, (min-width: 0px) 323px"
  podcast_thumb: "(min-width: 768px) 330px, (min-width: 480px) 200px, (min-width: 0px) 100vw"
  episode_thumb: "(min-width: 768px) 120px, (min-width: 0px) 80px"
  album_thumb: "96px"
  song_artwork: "(min-width: 992px) 360px, (min-width: 0px) 100vw"
  avatar: "80px"
  full_width: "100vw"
  half_width: "50vw"
  one_hundred: "100%"
  topic_feature_sub: "(min-width: 992px) 370px, (min-width: 0px) 100px"

typekit_url: https://use.typekit.net/ccb3vpa.css
