# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Crossroads Media
email: info@crossroads.net
description: >- # this means to ignore newlines until "baseurl:"
  No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-livereload
  - jekyll-contentful-data-import
  - jekyll-redirect-from

sass:
  sass_dir: _scss

contentful:
  spaces:
    - crds: # Jekyll _data folder identifier - Required
        space: 6xtqh9zzbhsk                   # Required
        access_token: d47a0d6ca1eed38cc63f08e336f2979d60535b6f9dea06cf993c6085957552ad  # Required
        # cda_query:                  # Optional
        #   include: 2
        #   limit: 100
        # all_entries: true           # Optional - Defaults to false, only grabbing the amount set on CDA Query
        # all_entries_page_size: 1000 # Optional - Defaults to 1000, maximum amount of entries per CDA Request for all_entries
        # content_types:              # Optional
        #   cat: MyCoolMapper
        # client_options:             # Optional
        #   api_url: 'preview.contentful.com' # Defaults to 'api.contentful.com' which is Production
        #   max_include_resolution_depth: 5 # Optional - Defaults to 20, maximum amount of levels to resolve includes
        # base_path: app_path         # Optional - Defaults to Current directory
        destination: / # Optional - Defaults to _data/contentful/spaces
        # individual_entry_files: true # Optional - Defaults to false

page_gen-dirs: true
page_gen:
  - index_files: true
    data: 'crds.post'
    template: 'article'
    name: 'slug'
    dir: 'blog'

# Server Config options
# livereload: true
# reload_port: 4300

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
    - package.json
    - README.md

include:
  - _redirects
