title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com

# disable_hubspot: true

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-contentful
  - jekyll-paginate-v2

sass:
  sass_dir: _scss

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 16
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

# livereload: true
# reload_port: 4300

# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

include:
  - _redirects

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /articles/:path
  topics:
    output: true
    permalink: /topics/:path
  authors:
    output: true
    permalink: /:collection/:path

contentful:
  content_types:
    posts:
      id: post
      body: body
      frontmatter:
        entry_mappings:
          title: name
          featured_image: featured_image/url
          author: author/name
          topic: category/name
          date: published_date
        other:
          layout: post
          draft: false
    authors:
      id: authors
      body: bio
      frontmatter:
        entry_mappings:
          title: name
          name: name
          image: profile_image/url
        other:
          layout: author
          draft: false
    topics:
      id: category
      frontmatter:
        entry_mappings:
          title: name
          name: name
        other:
          layout: topic
          draft: false

defaults:
  - scope:
      path: "/articles"
      type: posts
    values:
      layout: post
  - scope:
      path: "/topics"
      type: topics
    values:
      layout: topic
  - scope:
      path: "/authors"
      type: authors
    values:
      layout: author
