title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com

# disable_hubspot: true
permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-hubspot

sass:
  sass_dir: _scss

# livereload: true
# reload_port: 4300

# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

include:
  - _redirects

collections_dir: collections

collections:
  blogs:
    output: true
    permalink: /topics/:path
  authors:
    output: true
    permalink: /authors/:path

hubspot:
  blogs:
    layout: topic
    properties:
      id: id
      title: name
      content: description
  posts:
    layout: post
    properties:
      title: title
      content: post_body
      featured_image: featured_image
      author: blog_post_author/display_name
      date: publish_date
      topic: topics
  authors:
    layout: author
    properties:
      content: bio
      title: displayName
      name: displayName
      image: avatar

defaults:
  - scope:
      path: "/topics/"
      type: topics
    values:
      layout: topic
  - scope:
      path: "/authors/"
      type: authors
    values:
      layout: author

