title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 24
paginate_path: "/page:num/"

sass:
  sass_dir: _scss

# livereload: true
# reload_port: 4300

# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md

include:
  - _redirects

collections_dir: collections

collections:
  topics:
    output: true
    permalink: /topics/:path/
  authors:
    output: true
    permalink: /authors/:path/

defaults:
  - scope:
      path: "/topics/"
      type: topics
    values:
      layout: topic
  - scope:
      path: "/authors/"
      type: authors
    values:
      layout: author
