[build]
  command = '''
    npm i -g purgecss &&
    bundle exec jekyll crds &&
    bundle exec jekyll contentful &&
    bundle exec rspec ./vendor -r ./spec/support/jekyll_helper.rb &&
    bundle exec jekyll build
  '''
